import test from 'node:test';
import assert from 'node:assert/strict';
import { ensureMaterialVersion, claimMaterial, markMaterialSucceeded, markMaterialFailed, setCurrentMaterial, getCurrentMaterial, resetFailedMaterial } from '../functions/_lib/material-store.js';
import { materialKeys, validateManifestBytes } from '../functions/_lib/material-state.js';
import { signMaterialsToken, verifyMaterialsToken, signedMaterialUrls } from '../functions/_lib/signing.js';

class R2Fake { constructor(){ this.objects=new Map(); } async put(k,v){ this.objects.set(k,String(v)); } async head(k){ return this.objects.has(k)?{key:k}:null; } async get(k){ const v=this.objects.get(k); if(v===undefined)return null; return { text:async()=>v, arrayBuffer:async()=>new TextEncoder().encode(v).buffer }; } }
function dbFetch(){ const rows=new Map(); let next=1; globalThis.fetch=async (_url,init)=>{ const req=JSON.parse(init.body).requests[0]; const sql=req.stmt.sql; const args=req.stmt.args.map(a=>a.value); let result; if(sql.startsWith('INSERT INTO material_versions')){ const key=args[0]+':'+args[1]; if(!rows.has(key)) rows.set(key,{id:next++,job_id:args[0],version:args[1],state:'pending',source_exists:0,hard_gates_pass:0,attempt_count:0}); result={affected_row_count:1}; } else if(sql.startsWith('SELECT * FROM material_versions')){ { const row=[...rows.values()].find(r=>String(r.job_id)===String(args[0])&&r.version===args[1]); const cols=['id','job_id','version','state','source_exists','hard_gates_pass','attempt_count','lease_token','artifact_prefix']; result={cols,rows:row?[[row.id,row.job_id,row.version,row.state,row.source_exists,row.hard_gates_pass,row.attempt_count,row.lease_token,row.artifact_prefix].map((value,i)=>({type:i===0||[4,5,6].includes(i)?'integer':'text',value:value??null}))]:[]}; } } else if(sql.includes('UPDATE material_versions SET state=\'claimed\'')){ const r=[...rows.values()].find(x=>String(x.job_id)===String(args[2])&&x.version===args[3]); const ok=r && (r.state==='pending'||r.state==='claimed'); if(ok){r.state='claimed';r.lease_token=args[0];r.attempt_count++;} result={affected_row_count:ok?'1':'0'}; } else if(sql.includes("SET state='succeeded'")){ const r=[...rows.values()].find(x=>String(x.job_id)===String(args[1])&&x.version===args[2]); const ok=r?.state==='claimed'&&r.lease_token===args[3]; if(ok){r.state='succeeded';r.source_exists=1;r.hard_gates_pass=1;r.artifact_prefix=args[0];} result={affected_row_count:ok?1:0}; } else if(sql.includes("SET state='failed'")){ result={affected_row_count:0}; } else if(sql.includes('material_current')){ result={affected_row_count:0}; } else result={affected_row_count:0}; return new Response(JSON.stringify({results:[{type:'ok',response:{result}}]}),{headers:{'content-type':'application/json'}}); }; return rows; }

test('store helpers fence claims, terminal updates, prefixes and R2 bytes', async()=>{ const db=dbFetch(); const env={TURSO_URL:'http://fake',TURSO_TOKEN:'x'}; const r2=new R2Fake(); await ensureMaterialVersion(env,{jobId:7,version:'a'.repeat(64)}); const c=await claimMaterial(env,{jobId:7,version:'a'.repeat(64),leaseToken:'lease'}); assert.equal(c.claimed,true); assert.equal((await markMaterialSucceeded(env,{jobId:7,version:'a'.repeat(64),leaseToken:'stale',artifactPrefix:'bad'})),false); assert.equal((await markMaterialSucceeded(env,{jobId:7,version:'a'.repeat(64),leaseToken:'lease',artifactPrefix:'materials/7/versions/a'.padEnd(80,'x')})),true); assert.equal((await resetFailedMaterial(env,{jobId:7,version:'a'.repeat(64)})),false); const k=materialKeys(7,'a'.repeat(64)); await r2.put(k.resume,'r'); assert.ok(await r2.head(k.resume)); assert.equal(await (await r2.get(k.resume)).text(), 'r'); assert.ok(db); });

test('fake R2 partial and tampered objects fail closed', async()=>{ const r2=new R2Fake(); await r2.put('x','good'); assert.equal(await (await r2.get('x')).text(), 'good'); assert.equal(new TextDecoder().decode(await (await r2.get('x')).arrayBuffer()), 'good'); assert.equal(await r2.get('missing'),null); await r2.put('x','tampered'); assert.equal(await (await r2.get('x')).text(), 'tampered'); });

test('typed rows, affected counts, pointer and version-bound signing', async()=>{ const env={TURSO_URL:'http://fake',TURSO_TOKEN:'x'}; const version='a'.repeat(64); dbFetch(); const row=await ensureMaterialVersion(env,{jobId:8,version}); assert.equal(row.version,version); const claim=await claimMaterial(env,{jobId:8,version,leaseToken:'t'}); assert.equal(claim.claimed,true); assert.equal(await markMaterialSucceeded(env,{jobId:8,version,leaseToken:'wrong',artifactPrefix:'x'}),false); assert.equal(await markMaterialSucceeded(env,{jobId:8,version,leaseToken:'t',artifactPrefix:'materials/8/versions/a'}),true); const token=await signMaterialsToken({MATERIALS_SIGNING_KEY:'test'},8,'resume.md',60,version); assert.equal(await verifyMaterialsToken({MATERIALS_SIGNING_KEY:'test'},8,'resume.md',token,version),true); assert.equal(await verifyMaterialsToken({MATERIALS_SIGNING_KEY:'test'},8,'cover_letter.md',token,version),false); const urls=await signedMaterialUrls({MATERIALS_SIGNING_KEY:'test'},8,60,version); assert.match(urls.resume,/versions\/a{64}\/resume\.md/); assert.ok(row); });

test('manifest actual bytes reject mismatch', async()=>{ const version='b'.repeat(64), bytes={resume:'r',coverLetter:'c',details:'d'}; const digest=async x=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(x)))].map(b=>b.toString(16).padStart(2,'0')).join(''); const m={job_id:9,version,profile_revision:'p',template_revision:'t',renderer_revision:'r',artifacts:{resume:await digest('r'),cover_letter:await digest('c'),job_details:await digest('d')}}; assert.equal(await validateManifestBytes(m,bytes,{jobId:9,version}),true); assert.equal(await validateManifestBytes(m,{...bytes,coverLetter:'bad'},{jobId:9,version}),false); });
