import test from 'node:test';
import assert from 'node:assert/strict';
import { ensureMaterialVersion, claimMaterial, markMaterialSucceeded, markMaterialFailed, setCurrentMaterial, getCurrentMaterial, resetFailedMaterial } from '../functions/_lib/material-store.js';
import { materialKeys } from '../functions/_lib/material-state.js';

class R2Fake { constructor(){ this.objects=new Map(); } async put(k,v){ this.objects.set(k,String(v)); } async head(k){ return this.objects.has(k)?{key:k}:null; } async get(k){ const v=this.objects.get(k); if(v===undefined)return null; return { text:async()=>v, arrayBuffer:async()=>new TextEncoder().encode(v).buffer }; } }
function dbFetch(){ const rows=new Map(); let next=1; globalThis.fetch=async (_url,init)=>{ const req=JSON.parse(init.body).requests[0]; const sql=req.stmt.sql; const args=req.stmt.args.map(a=>a.value); let result; if(sql.startsWith('INSERT INTO material_versions')){ const key=args[0]+':'+args[1]; if(!rows.has(key)) rows.set(key,{id:next++,job_id:args[0],version:args[1],state:'pending',source_exists:0,hard_gates_pass:0,attempt_count:0}); result={affected_row_count:1}; } else if(sql.startsWith('SELECT * FROM material_versions')){ result={cols:[],rows:[[...rows.values()].find(r=>String(r.job_id)===String(args[0])&&r.version===args[1])].filter(Boolean).map(r=>Object.values(r))}; } else if(sql.includes('UPDATE material_versions SET state=\'claimed\'')){ const r=[...rows.values()].find(x=>String(x.job_id)===String(args[2])&&x.version===args[3]); const ok=r && (r.state==='pending'||r.state==='claimed'); if(ok){r.state='claimed';r.lease_token=args[0];r.attempt_count++;} result={affected_row_count:ok?'1':'0'}; } else if(sql.includes("SET state='succeeded'")){ const r=[...rows.values()].find(x=>String(x.job_id)===String(args[1])&&x.version===args[2]); const ok=r?.state==='claimed'&&r.lease_token===args[3]; if(ok){r.state='succeeded';r.source_exists=1;r.hard_gates_pass=1;r.artifact_prefix=args[0];} result={affected_row_count:ok?1:0}; } else if(sql.includes("SET state='failed'")){ result={affected_row_count:0}; } else if(sql.includes('material_current')){ result={affected_row_count:0}; } else result={affected_row_count:0}; return new Response(JSON.stringify({results:[{type:'ok',response:{result}}]}),{headers:{'content-type':'application/json'}}); }; return rows; }

test('store helpers fence claims, terminal updates, prefixes and R2 bytes', async()=>{ const db=dbFetch(); const env={TURSO_URL:'http://fake',TURSO_TOKEN:'x'}; const r2=new R2Fake(); await ensureMaterialVersion(env,{jobId:7,version:'a'.repeat(64)}); const c=await claimMaterial(env,{jobId:7,version:'a'.repeat(64),leaseToken:'lease'}); assert.equal(c.claimed,true); assert.equal((await markMaterialSucceeded(env,{jobId:7,version:'a'.repeat(64),leaseToken:'stale',artifactPrefix:'bad'})),false); assert.equal((await markMaterialSucceeded(env,{jobId:7,version:'a'.repeat(64),leaseToken:'lease',artifactPrefix:'materials/7/versions/a'.padEnd(80,'x')})),true); assert.equal((await resetFailedMaterial(env,{jobId:7,version:'a'.repeat(64)})),false); const k=materialKeys(7,'a'.repeat(64)); await r2.put(k.resume,'r'); assert.ok(await r2.head(k.resume)); assert.equal(await (await r2.get(k.resume)).text(), 'r'); assert.ok(db); });

test('fake R2 partial and tampered objects fail closed', async()=>{ const r2=new R2Fake(); await r2.put('x','good'); assert.equal(await (await r2.get('x')).text(), 'good'); assert.equal(await r2.get('missing'),null); await r2.put('x','tampered'); assert.equal(await (await r2.get('x')).text(), 'tampered'); });
