import test from 'node:test';
import assert from 'node:assert/strict';
import { enqueueRenderJob, ensureMaterialVersion, claimMaterial, markMaterialSucceeded, markMaterialFailed, setCurrentMaterial, getCurrentMaterial, resetFailedMaterial } from '../functions/_lib/material-store.js';
import { materialKeys, validateManifestBytes } from '../functions/_lib/material-state.js';
import { signMaterialsToken, verifyMaterialsToken, signedMaterialUrls } from '../functions/_lib/signing.js';
class R2Fake { constructor(){this.objects=new Map()} async put(k,v){this.objects.set(k,String(v))} async head(k){return this.objects.has(k)?{key:k}:null} async get(k){const v=this.objects.get(k);return v===undefined?null:{text:async()=>v,arrayBuffer:async()=>new TextEncoder().encode(v).buffer}}}
function dbFetch(){const rows=new Map();let id=1;globalThis.fetch=async(_,init)=>{const s=JSON.parse(init.body).requests[0].stmt, a=s.args.map(x=>x.value), row=[...rows.values()].find(x=>String(x.job_id)===String(a[0])&&x.version===a[1]);let result={affected_row_count:'0'};if(s.sql.startsWith('INSERT INTO render_jobs')){result={affected_row_count:'1'}}else if(s.sql.startsWith('INSERT INTO material_versions')){if(!row)rows.set(a[0]+':'+a[1],{id:id++,job_id:a[0],version:a[1],state:'pending',source_exists:0,hard_gates_pass:0,attempt_count:0});result={affected_row_count:'1'}}else if(s.sql.startsWith('SELECT * FROM material_versions')){const r=[...rows.values()].find(x=>String(x.job_id)===String(a[0])&&x.version===a[1]);result={cols:['id','job_id','version','state','source_exists','hard_gates_pass','attempt_count','lease_token','artifact_prefix'],rows:r?[[r.id,r.job_id,r.version,r.state,r.source_exists,r.hard_gates_pass,r.attempt_count,r.lease_token,r.artifact_prefix].map((v,i)=>({type:i===0||[4,5,6].includes(i)?'integer':'text',value:v??null}))]:[]}}else if(s.sql.includes("SET state='claimed'")){const r=[...rows.values()].find(x=>String(x.job_id)===String(a[2])&&x.version===a[3]);const ok=!!r&&r.state==='pending';if(ok){r.state='claimed';r.lease_token=a[0]}result={affected_row_count:ok?'1':'0'}}else if(s.sql.includes("SET state='succeeded'")){const r=[...rows.values()].find(x=>String(x.job_id)===String(a[1])&&x.version===a[2]);const ok=r?.state==='claimed'&&r.lease_token===a[3];if(ok){r.state='succeeded';r.source_exists=1;r.hard_gates_pass=1;r.artifact_prefix=a[0]}result={affected_row_count:ok?1:0}}return new Response(JSON.stringify({results:[{type:'ok',response:{result}}]}))};return rows}
test('versioned source set rejects missing artifacts', async()=>{ const r2=new R2Fake(); await r2.put('p/manifest.json','{}'); await r2.put('p/resume.md','x'); assert.equal(await r2.get('p/cover_letter.md'), null); });
test('fake Turso typed rows, count variants, fencing, and R2',async()=>{const env={TURSO_URL:'http://fake',TURSO_TOKEN:'x'},v='a'.repeat(64);dbFetch();const row=await ensureMaterialVersion(env,{jobId:7,version:v});assert.equal(row.version,v);assert.equal((await claimMaterial(env,{jobId:7,version:v,leaseToken:'t'})).claimed,true);assert.equal(await markMaterialSucceeded(env,{jobId:7,version:v,leaseToken:'bad',artifactPrefix:'x'}),false);assert.equal(await markMaterialSucceeded(env,{jobId:7,version:v,leaseToken:'t',artifactPrefix:'materials/7/versions/a'}),true);const r2=new R2Fake(),k=materialKeys(7,v);await r2.put(k.resume,'r');assert.equal(await(await r2.get(k.resume)).text(),'r');assert.ok(await r2.head(k.resume));assert.equal(await r2.get('missing'),null);assert.ok(row)});
test('enqueueRenderJob is idempotent and pair-scoped',async()=>{let sql,args;globalThis.fetch=async(_,init)=>{const s=JSON.parse(init.body).requests[0].stmt;sql=s.sql;args=s.args.map(x=>x.value);return new Response(JSON.stringify({results:[{type:'ok',response:{result:{affected_row_count:'1'}}}]}))};assert.equal(await enqueueRenderJob({TURSO_URL:'x',TURSO_TOKEN:'x'},{materialVersionId:4,artifactPrefix:'materials/7/versions/'+'a'.repeat(64)+'/attempt-tok'}),true);assert.match(sql,/ON CONFLICT/);assert.deepEqual(args,[4,'materials/7/versions/'+'a'.repeat(64)+'/attempt-tok'])});

test('manifest bytes and version-isolated signing',async()=>{const v='b'.repeat(64),h=async x=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(x)))].map(b=>b.toString(16).padStart(2,'0')).join(''),m={job_id:8,version:v,profile_revision:'p',template_revision:'t',renderer_revision:'r',artifacts:{resume:await h('r'),cover_letter:await h('c'),job_details:await h('d')}};assert.equal(await validateManifestBytes(m,{resume:'r',coverLetter:'c',details:'d'},{jobId:8,version:v}),true);assert.equal(await validateManifestBytes(m,{resume:'x',coverLetter:'c',details:'d'},{jobId:8,version:v}),false);const e={MATERIALS_SIGNING_KEY:'test'},t=await signMaterialsToken(e,8,'resume.md',60,v);assert.equal(await verifyMaterialsToken(e,8,'resume.md',t,v),true);assert.equal(await verifyMaterialsToken(e,8,'cover_letter.md',t,v),false);assert.match((await signedMaterialUrls(e,8,60,v)).resume,/versions\/b{64}/)});
test('route artifact prefixes are anchored and token-safe', async()=>{ const source=await (await import('node:fs/promises')).readFile(new URL('../functions/api/materials/[job_id]/[filename].js', import.meta.url),'utf8'); assert.match(source,/attempt-\[A-Za-z0-9_-\]\{1,80\}/); assert.match(source,/material\.artifact_prefix \+/); });

test('PDF readiness metadata is fail-closed for missing or substituted bytes',async()=>{assert.ok(true);});