import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {safeMarkdown,renderMaterials,hardGates,renderPdf,loadTemplates} from '../scripts/materials-renderer.mjs';
const t={resume:'{{name}} {{email}} {{phone}} {{location}} {{resume}}',cover:'{{name}} {{cover}}'};
const fixture=()=>JSON.parse(fs.readFileSync('tests/fixtures/materials/short.json'));
test('rendering, escaping, deterministic revisions',()=>{const d=fixture(),a=renderMaterials(d,t),b=renderMaterials(d,t);assert.equal(a.revision,b.revision);assert.doesNotMatch(a.resume,/{{/);assert.match(a.resume,/&amp;/);d.resume.markdown+=' changed';assert.notEqual(renderMaterials(d,t).revision,a.revision);});
test('strict validation and sanitizer allowlist',()=>{for(const x of [null,[],{}, {resume:{name:'x',markdown:'x'},cover:{markdown:'x'}}])assert.throws(()=>renderMaterials(x,t));const attack='<!--x--><script>bad</script><style>x</style><noscript>x</noscript><iframe>x</iframe><object>x</object>\n![x](data:image/png,x) [js](javascript:alert(1)) [remote](https://x.test)';const clean=safeMarkdown(attack);assert.doesNotMatch(clean,/<script|style|noscript|iframe|object|data:|javascript:|https?:|src=|href=|url\(|@import/i);assert.throws(()=>renderMaterials(fixture(),{resume:'{{unknown}}',cover:t.cover}));});
test('dense fixture and derived hard gates',()=>{assert.ok(renderMaterials(JSON.parse(fs.readFileSync('tests/fixtures/materials/dense.json')),t).resume.length>100);for(const x of ['\uFFFD','overflow','clipped'])assert.equal(hardGates({type:'resume',text:x,pages:1,networkRequests:0}).ok,false);assert.equal(hardGates({type:'resume',text:'x',pages:3,networkRequests:0}).ok,false);assert.equal(hardGates({type:'resume',text:'x',pages:1}).ok,false);assert.equal(hardGates({type:'resume',text:'x',pages:1,networkRequests:0}).ok,true);assert.equal(hardGates({type:'resume',text:'x',pages:1,networkRequests:undefined}).ok,false);});
test('fake PDF runner, unavailable browser, atomic preservation',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'materials-test-')),dest=path.join(dir,'old.pdf');fs.writeFileSync(dest,'old');const runner=(cmd,args)=>{if(cmd==='pdfinfo')return 'Pages: 1\n';if(cmd==='pdftotext')return 'Thank you.\n';fs.writeFileSync(args.find(x=>x.startsWith('--print-to-pdf=')).slice(15),'PDF');};const out=renderPdf('<html><body>x</body></html>',{browser:'fake',runner,destination:dest,outputDir:dir});assert.equal(out.ok,true);assert.equal(fs.readFileSync(dest,'utf8'),'PDF');assert.equal(renderPdf('<html>x</html>',{browser:null}).available,false);fs.rmSync(dir,{recursive:true,force:true});});
// Regression: pdftotext separates pages with \f (and single-page output still
// ends with one); those are extraction artifacts, not font tofu. The first
// live canary failed every PDF on this exact character.
test('pdftotext form-feed page separators do not trip the tofu gate',()=>{const page='Arshad Kazi did the work.\n';assert.equal(hardGates({type:'resume',text:page+'\f'+page,pages:2,networkRequests:0}).ok,true);assert.equal(hardGates({type:'cover_letter',text:page+'\f',pages:1,networkRequests:0}).ok,true);assert.equal(hardGates({type:'resume',text:page+'\f'+'real \uFFFD tofu',pages:2,networkRequests:0}).ok,false);});
test('duplicate name/contact header in markdown is stripped from the resume projection',()=>{const t=loadTemplates();const md='# Arshad Kazi\n**Regional Sales Manager**\n\nWaterdown, ON | 416-316-9864 | arshad@arshadkazi.ca\nlinkedin.com/in/arshadkazi1\n\n---\n\n## EXPERIENCE\n- Did A\n';const out=renderMaterials({name:'Arshad Kazi',email:'arshad@arshadkazi.ca',phone:'416-316-9864',location:'Waterdown, ON',resume:{markdown:md},coverLetter:{markdown:'Dear team,'}},t);const text=out.resume;assert.equal((text.match(/Arshad Kazi/g)||[]).length,1,'template header only');assert.doesNotMatch(text,/linkedin\.com/);assert.equal((text.match(/416-316-9864/g)||[]).length,1,'template contact line only');assert.match(text,/Regional Sales Manager/);assert.match(text,/EXPERIENCE/);assert.match(text,/Did A/);});
test('non-matching leading H1 is preserved',()=>{const t=loadTemplates();const md='# Someone Else Entirely\n\n## Summary\n- Did B\n';const out=renderMaterials({name:'Arshad Kazi',email:'a@x.test',phone:'555',location:'X',resume:{markdown:md},coverLetter:{markdown:'Dear,'}},t);assert.match(out.resume,/Someone Else Entirely/);});
test('prose mentioning GitHub and normal summary lines survive the strip',()=>{const t=loadTemplates();const md='# Arshad Kazi\n\nAutomotive leader who shipped tools on GitHub for the dealer network.\n\n## SUMMARY\n- Did C\n';const out=renderMaterials({name:'Arshad Kazi',email:'a@x.test',phone:'5555555555',location:'Toronto, ON',resume:{markdown:md},coverLetter:{markdown:'Dear,'}},t);assert.match(out.resume,/GitHub for the dealer network/);assert.match(out.resume,/SUMMARY/);});
test('cover letter duplicate header is stripped too',()=>{const t=loadTemplates();const md='# Arshad Kazi\n\nWaterdown, ON | 416-316-9864 | a@x.test | linkedin.com/in/arshadkazi1\n\nDear Hiring Manager,\n\nBody text.\n';const out=renderMaterials({name:'Arshad Kazi',email:'a@x.test',phone:'416-316-9864',location:'Toronto, ON',resume:{markdown:'# Arshad Kazi\n\n- Did A\n'},coverLetter:{markdown:md}},t);assert.equal((out.cover.match(/Arshad Kazi/g)||[]).length,1,'template header only');assert.doesNotMatch(out.cover,/linkedin\.com/);assert.match(out.cover,/Dear Hiring Manager/);});
test('standalone city-province line in the header region is stripped',()=>{const t=loadTemplates();const md='# Arshad Kazi\n\nWaterdown, ON, Canada\n\nDear Hiring Manager,\n\nBody.\n';const out=renderMaterials({name:'Arshad Kazi',email:'a@x.test',phone:'5555555555',location:'Waterdown, Ontario, Canada',resume:{markdown:'- Did A'},coverLetter:{markdown:md}},t);assert.doesNotMatch(out.cover,/Waterdown, ON, Canada/);assert.match(out.cover,/Dear Hiring Manager/);});
