import test from 'node:test';
import assert from 'node:assert/strict';
import { runPreflight } from '../scripts/preflight.mjs';
import { spawnSync } from 'node:child_process';
const base = { ...process.env };
const configured = { ...base, TURSO_URL:'https://example.test', TURSO_TOKEN:'secret', NINEROUTER_API_KEY:'secret', DASHBOARD_AUTH_TOKEN:'secret', JOB_MATERIALS_BUCKET:'bucket', R2_ENDPOINT:'https://example.test', R2_ACCESS_KEY_ID:'secret', R2_SECRET_ACCESS_KEY:'secret', R2_BUCKET:'bucket' };
const commands = () => true;
const chromium = () => 'chromium';
const allChecks = (r) => assert.equal(r.ok, true);
test('preflight reports env and command checks without values', () => { const r = runPreflight(configured, commands, chromium); allChecks(r); assert.deepEqual(r.commands, {node:true,pdftotext:true,pdfinfo:true,chromium:true}); });
test('preflight rejects missing R2 credentials', () => { const env = { ...configured }; delete env.R2_ACCESS_KEY_ID; const r = runPreflight(env, commands, chromium); assert.equal(r.ok, false); assert.equal(r.checks.R2_ACCESS_KEY_ID, false); });
test('preflight rejects non-https R2 endpoints', () => { const r = runPreflight({ ...configured, R2_ENDPOINT:'http://insecure.test' }, commands, chromium); assert.equal(r.ok, false); assert.equal(r.checks.R2_ENDPOINT, false); });
test('preflight rejects missing pdfinfo and chromium', () => { let r = runPreflight(configured, (c) => c !== 'pdfinfo', chromium); assert.equal(r.ok, false); assert.equal(r.commands.pdfinfo, false); r = runPreflight(configured, commands, () => null); assert.equal(r.ok, false); assert.equal(r.commands.chromium, false); });
test('preflight validates CHROMIUM_BIN through the version probe, not by presence', () => { let seen; const r = runPreflight({ ...configured, CHROMIUM_BIN:'/opt/nonexistent-chromium' }, commands, (env) => { seen = env.CHROMIUM_BIN; return null; }); assert.equal(seen, '/opt/nonexistent-chromium'); assert.equal(r.commands.chromium, false); });
test('preflight rejects R2 endpoints without a parseable host', () => { const r = runPreflight({ ...configured, R2_ENDPOINT:'https://' }, commands, chromium); assert.equal(r.checks.R2_ENDPOINT, false); assert.equal(r.ok, false); });
test('preflight preserves inherited env and allows explicit deletion', () => { const env = { ...base }; for (const key of ['TURSO_URL','TURSO_TOKEN','R2_ENDPOINT','R2_ACCESS_KEY_ID','R2_SECRET_ACCESS_KEY','R2_BUCKET']) delete env[key]; const r = runPreflight(env, commands, chromium); assert.equal(r.ok, false); });
test('pages-only secrets are informational and do not gate a render host', () => { const env = { ...configured }; for (const key of ['NINEROUTER_API_KEY','DASHBOARD_AUTH_TOKEN','JOB_MATERIALS_BUCKET']) delete env[key]; const r = runPreflight(env, commands, chromium); assert.equal(r.ok, true); assert.deepEqual(r.pages, { NINEROUTER_API_KEY:false, DASHBOARD_AUTH_TOKEN:false, JOB_MATERIALS_BUCKET:false }); });
test('CLI JSON redacts secret values', () => { const r = spawnSync(process.execPath, ['scripts/preflight.mjs','--json'], { env: { ...configured }, encoding:'utf8' }); assert.doesNotMatch(r.stdout, /secret/); });
