import test from 'node:test';import assert from 'node:assert/strict';import {r2Config} from '../scripts/lib/r2-s3.mjs';
test('R2 config rejects incomplete or insecure settings',()=>{assert.throws(()=>r2Config({}),/missing R2_ENDPOINT/);assert.throws(()=>r2Config({R2_ENDPOINT:'http://x',R2_ACCESS_KEY_ID:'a',R2_SECRET_ACCESS_KEY:'b',R2_BUCKET:'c'}),/https/);assert.equal(r2Config({R2_ENDPOINT:'https://x',R2_ACCESS_KEY_ID:'a',R2_SECRET_ACCESS_KEY:'b',R2_BUCKET:'c'}).bucket,'c')});
test('signs and performs object methods',async()=>{let calls=[];const fetcher=async(url,init)=>{calls.push({url:String(url),init});return new Response('x',{status:200,headers:{'content-length':'1'}})};const {createR2S3}=await import('../scripts/lib/r2-s3.mjs');const b=createR2S3({R2_ENDPOINT:'https://r2.example.test',R2_ACCESS_KEY_ID:'id',R2_SECRET_ACCESS_KEY:'secret',R2_BUCKET:'bucket'},fetcher);const x=await b.get('a/b');assert.equal(await x.text(),'x');await b.head('a');await b.put('a',new Uint8Array([1]),{onlyIfNew:true});await b.delete('a');assert.equal(calls.length,4);assert.match(calls[0].init.headers.authorization,/AWS4-HMAC-SHA256/);assert.equal(calls[2].init.headers['if-none-match'],'*')});
// Regression: the signature must be HMAC over the full string-to-sign
// (algorithm, date, scope, canonical-request hash) per the SigV4 spec —
// the original implementation HMAC'd the canonical hash alone, which real
// R2 rejected with SignatureDoesNotMatch while mocked tests still passed.
test('signature covers the SigV4 string-to-sign, not the bare canonical hash',async()=>{let captured;const fetcher=async(url,init)=>{captured={url:String(url),init};return new Response('x',{status:200})};const {createR2S3}=await import('../scripts/lib/r2-s3.mjs');const env={R2_ENDPOINT:'https://r2.example.test',R2_ACCESS_KEY_ID:'AKIDEXAMPLE',R2_SECRET_ACCESS_KEY:'wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY',R2_BUCKET:'bucket'};const b=createR2S3(env,fetcher);await b.get('a/b');const h=captured.init.headers;const amzDate=h['x-amz-date'];const day=amzDate.slice(0,8);const payloadHash=h['x-amz-content-sha256'];const canonical=['host:r2.example.test','x-amz-content-sha256:'+payloadHash,'x-amz-date:'+amzDate].map(l=>l+'\n').join('');const creq='GET\n/bucket/a/b\n\n'+canonical+'\nhost;x-amz-content-sha256;x-amz-date\n'+payloadHash;const scope=day+'/auto/s3/aws4_request';const stringToSign='AWS4-HMAC-SHA256\n'+amzDate+'\n'+scope+'\n'+await sha256(creq);const expected=await hmacHex(await deriveKey(env.R2_SECRET_ACCESS_KEY,day),stringToSign);assert.equal(h.authorization,'AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/'+scope+', SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature='+expected)});
const enc=new TextEncoder();const toHex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha256(s){return toHex(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function hmacRaw(key,s){return new Uint8Array(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']),enc.encode(s)))}
async function hmacHex(key,s){return toHex(await hmacRaw(key,s))}
async function deriveKey(secret,day){let k=await hmacRaw(enc.encode('AWS4'+secret),day);k=await hmacRaw(k,'auto');k=await hmacRaw(k,'s3');return await hmacRaw(k,'aws4_request')}