import test from 'node:test';
import assert from 'node:assert/strict';
import { claimable, retryAfter, pollRenderJobs, processRenderJob, claimSql, MAX_ATTEMPTS } from '../scripts/render-jobs.mjs';
const enc=new TextEncoder();
async function hash(x){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(x)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
function fake(row){const objects=new Map();const puts=[];let live=true;const bucket={get:async k=>objects.has(k)?{arrayBuffer:async()=>objects.get(k)}:null,head:async k=>objects.has(k),put:async(k,b,o)=>{if(o.onlyIfNew&&objects.has(k))throw Error('exists');objects.set(k,typeof b==='string'?enc.encode(b):b);puts.push(k)}};const query=async()=>live?[{ok:1}]:[];const exec=async(e,sql,args)=>({affectedRowCount:live?1:0});return {bucket,query,exec,puts,objects,kill:()=>{live=false}}}
function seed(f,row){const p=row.artifact_prefix;const r='resume',c='cover',d='{}';const m={job_id:row.job_id,version:row.version,profile_revision:'p',template_revision:'t',renderer_revision:'r',artifacts:{resume:null,cover_letter:null,job_details:null}};return Promise.all([hash(r),hash(c),hash(d)]).then(([a,b,x])=>{m.artifacts={resume:a,cover_letter:b,job_details:x};for(const [n,v] of [['manifest.json',JSON.stringify(m)],['resume.md',r],['cover_letter.md',c],['job_details.json',d]])f.objects.set(p+'/'+n,enc.encode(v))})}
const row={id:1,job_id:7,version:'a'.repeat(64),lease_token:'tok',lease_expires_at:'2099-01-01',attempt_count:1,artifact_prefix:'materials/7/versions/'+'a'.repeat(64)+'/tok'};
test('claim and retry policy',async()=>{assert.equal(claimable({state:'pending',attempt_count:0}),true);assert.equal(claimable({state:'claimed',attempt_count:0,lease_expires_at:'2000-01-01'}),true);assert.equal(claimable({state:'pending',attempt_count:MAX_ATTEMPTS}),false);assert.ok(retryAfter(2)>retryAfter(1));let writes=0;const x=await pollRenderJobs({env:{},dryRun:true,query:async()=>[{id:1,state:'pending',attempt_count:0}],execute:async()=>{writes++}});assert.equal(x.dryRun,true);assert.equal(writes,0);assert.match(claimSql(),/attempt_count<\?/)});
test('valid bytes render both then upload exactly two',async()=>{const f=fake(row);await seed(f,row);const seen=[];const out=await processRenderJob(row,{env:{},bucket:f.bucket,query:f.query,execute:f.exec,renderer:async(s,t)=>{seen.push(t);return{ok:true,body:enc.encode(t)}}});assert.equal(out.state,'succeeded');assert.deepEqual(seen,['resume','cover_letter']);assert.equal(f.puts.length,2)});
test('renderer failure performs zero puts',async()=>{const f=fake(row);await seed(f,row);const out=await processRenderJob(row,{env:{},bucket:f.bucket,query:f.query,execute:f.exec,renderer:async(s,t)=>({ok:t==='resume',body:'x'})});assert.equal(out.state,'failed');assert.equal(f.puts.length,0)});
test('tampered source and stale lease fail closed',async()=>{const f=fake(row);await seed(f,row);f.objects.set(row.artifact_prefix+'/resume.md',enc.encode('tampered'));assert.equal((await processRenderJob(row,{env:{},bucket:f.bucket,query:f.query,execute:f.exec,renderer:async()=>({ok:true,body:'x'})})).state,'failed');const g=fake(row);await seed(g,row);g.kill();assert.equal((await processRenderJob(row,{env:{},bucket:g.bucket,query:g.query,execute:g.exec,renderer:async()=>({ok:true,body:'x'})})).state,'stale')});

test('expiry during render causes no upload',async()=>{const f=fake(row);await seed(f,row);let first=true;const out=await processRenderJob(row,{env:{},bucket:f.bucket,query:async()=>{if(first){first=false;return[{ok:1}]}f.kill();return[]},execute:f.exec,renderer:async()=>({ok:true,body:'pdf'})});assert.equal(out.state,'stale');assert.equal(f.puts.length,0)});
test('existing PDF is never overwritten',async()=>{const f=fake(row);await seed(f,row);f.objects.set(row.artifact_prefix+'/resume.pdf',enc.encode('old'));const out=await processRenderJob(row,{env:{},bucket:f.bucket,query:f.query,execute:f.exec,renderer:async()=>({ok:true,body:'pdf'})});assert.equal(out.state,'failed');assert.equal(new TextDecoder().decode(f.objects.get(row.artifact_prefix+'/resume.pdf')),'old');assert.equal(f.puts.length,0)});
test('max attempt failure is terminal and bounded',async()=>{const f=fake({...row,attempt_count:MAX_ATTEMPTS});await seed(f,{...row,attempt_count:MAX_ATTEMPTS});let sql='';const out=await processRenderJob({...row,attempt_count:MAX_ATTEMPTS},{env:{},bucket:f.bucket,query:f.query,execute:async(e,s,a)=>{sql=s;return{affectedRowCount:1}},renderer:async()=>({ok:false})});assert.equal(out.state,'failed');assert.match(sql,/completed_at=datetime/);assert.match(sql,/retry_at=NULL/)})

test('failure schedules bounded retry and fenced SQL',async()=>{const f=fake(row);await seed(f,row);let sql,args;const out=await processRenderJob(row,{env:{},bucket:f.bucket,query:f.query,execute:async(e,s,a)=>{sql=s;args=a;return{affectedRowCount:1}},renderer:async()=>({ok:false,error:'bad\ninput'})});assert.equal(out.state,'failed');assert.match(sql,/retry_at=/);assert.match(sql,/lease_token=\?/);assert.equal(args.length,6)});
test('checkLease false prevents reads and writes',async()=>{const f=fake(row);await seed(f,row);let reads=0;f.bucket.checkLease=()=>false;const out=await processRenderJob(row,{env:{},bucket:{...f.bucket,get:async()=>{reads++;return null}},query:f.query,execute:f.exec,renderer:async()=>({ok:true,body:'pdf'})});assert.equal(out.state,'stale');assert.equal(reads,0)});