#!/usr/bin/env node
/** Bounded, deterministic, redacted operational report. */
import fs from 'node:fs';
import { tursoQuery } from './lib/turso.mjs';
export const MAX_ROWS=1000;
const validRows=x=>Array.isArray(x)?x.filter(r=>r&&typeof r==='object'&&!Array.isArray(r)).slice(0,MAX_ROWS):[];
const key=(v)=>/^[A-Za-z0-9_.:-]{1,40}$/.test(String(v??''))?String(v):'unknown';
const bucket=(rs,k)=>rs.reduce((a,r)=>(a[key(r[k])]=(a[key(r[k])]||0)+1,a),{});
const latency=rs=>{const v=rs.map(r=>Number(r.duration_ms)).filter(Number.isFinite).filter(n=>n>=0&&n<=86400000).sort((a,b)=>a-b);return{count:v.length,min_ms:v[0]??0,max_ms:v.at(-1)??0,avg_ms:v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0};};
export function summarize(input={}){const mats=validRows(input.material_versions||[]), render=validRows(input.render_jobs||[]), apps=validRows(input.applications||[]), now=Number.isFinite(input.now_ms)?input.now_ms:0;const stale=r=>r.state==='claimed'&&typeof r.lease_expires_at==='string'&&Number.isFinite(Date.parse(r.lease_expires_at))&&Date.parse(r.lease_expires_at)<now;return{generated_at:'deterministic',bounded:true,generation:{available:false,reason:'not_recorded_in_deployed_schema',latency:latency(mats),failures:mats.filter(r=>r.state==='failed').length,reuse:mats.filter(r=>r.reused_from_job_id!=null).length},render:{latency:latency(render),failures:render.filter(r=>r.state==='failed').length,queue_depth:render.filter(r=>['pending','claimed'].includes(r.state)).length,states:bucket(render,'state')},quality_gate:bucket(mats,'hard_gates_pass'),jd_source:{available:false,reason:'not_recorded_in_deployed_schema'},stale_lease:{materials:mats.filter(stale).length,render_jobs:render.filter(stale).length},counts:{applications:apps.length,materials:mats.length,render:render.length}};}
export function retentionGuard({versionedArtifactsLive=false,currentVersion,currentHash,requestedVersions=[],restoreProof=false}={}){const current=typeof currentVersion==='string'&&currentVersion.length>0,hash=typeof currentHash==='string'&&currentHash.length>0,nonCurrent=requestedVersions.every(v=>String(v)!==currentVersion);const allowed=Boolean(versionedArtifactsLive&&current&&hash&&restoreProof&&nonCurrent);return{allowed,destructive:false,reason:allowed?'guarded_non_current_restore_proven':'requires_live_versions_current_pointer_hash_restore_proof'};}
export async function loadReport({env=process.env,query=tursoQuery,input}={}){if(input)return summarize(input);if(!env.TURSO_URL||!env.TURSO_TOKEN)throw new Error('report configuration unavailable');const q=async(sql)=>{const rows=await query(env,sql,[MAX_ROWS]);return rows;};const [material_versions,render_jobs,applications]=await Promise.all([q('SELECT state,hard_gates_pass,lease_expires_at,reused_from_job_id FROM material_versions ORDER BY id DESC LIMIT ?'),q('SELECT state,lease_expires_at,duration_ms FROM render_jobs ORDER BY id DESC LIMIT ?'),q('SELECT status FROM applications ORDER BY id DESC LIMIT ?')]);return summarize({material_versions,render_jobs,applications});}
export function selfTest(){const r=summarize({now_ms:2000,material_versions:[{state:'failed',reused_from_job_id:2,hard_gates_pass:0}],render_jobs:[{state:'pending',duration_ms:2},{state:'claimed',lease_expires_at:'1970-01-01T00:00:01Z'}]});if(r.generation.available||r.generation.failures!==1||r.render.queue_depth!==2||r.stale_lease.render_jobs!==1||retentionGuard({versionedArtifactsLive:true,currentVersion:'v',currentHash:'h',requestedVersions:['x'],restoreProof:false}).allowed)throw new Error('health self-test failed');return r;}
if(import.meta.url==='file://'+process.argv[1]){try{const a=process.argv.slice(2),i=a.indexOf('--input');console.log(JSON.stringify(a.includes('--self-test')?selfTest():await loadReport({input:i>=0?JSON.parse(fs.readFileSync(a[i+1],'utf8')):undefined}),null,2));}catch{console.error('health report unavailable');process.exitCode=1;}}
