#!/usr/bin/env node
/** Bounded operational summary. It emits counters only: no documents, PII, secrets, or raw errors. */
import fs from 'node:fs';
import { tursoQuery } from './lib/turso.mjs';
export const MAX_ROWS = 1000;
const cap = x => Array.isArray(x) ? x.filter(r => r && typeof r === 'object' && !Array.isArray(r)).slice(0, MAX_ROWS) : [];
const bucket = (rows, key) => rows.reduce((a,r)=>{const raw=String(r[key] ?? 'unknown');const k=/^[A-Za-z0-9_.:-]{1,40}$/.test(raw)?raw:'unknown';a[k]=(a[k]||0)+1;return a;},{});
const latency = rows => { const v=rows.map(r=>Number(r.duration_ms ?? r.latency_ms)).filter(Number.isFinite).filter(x=>x>=0).sort((a,b)=>a-b); return {count:v.length,min_ms:v[0]??0,max_ms:v.at(-1)??0,avg_ms:v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0}; };
export function summarize(input={}) { const gen=cap(input.generation), render=cap(input.render_jobs), mats=cap(input.material_versions), now=input.now_ms??Date.now(); const stale=r=>r.state==='claimed'&&typeof r.lease_expires_at==='string'&&Number.isFinite(Date.parse(r.lease_expires_at))&&Date.parse(r.lease_expires_at)<now; return {generated_at:input.generated_at||'deterministic',bounded:true,generation:{latency:latency(gen),failures:gen.filter(r=>['failed','error'].includes(String(r.state))).length,reuse:gen.filter(r=>r.reused_from_job_id!=null||r.reused===true).length},render:{latency:latency(render),failures:render.filter(r=>r.state==='failed').length,queue_depth:render.filter(r=>['pending','claimed'].includes(r.state)).length,states:bucket(render,'state')},quality_gate:bucket(mats,'hard_gates_pass'),jd_source:bucket(gen,'jd_source'),stale_lease:{materials:mats.filter(stale).length,render_jobs:render.filter(stale).length},counts:{generation:gen.length,render:render.length,materials:mats.length}}; }
async function safe(query,env,sql,args){try{return await query(env,sql,args);}catch{return [];}}
export async function loadReport({env=process.env,query=tursoQuery,input}={}) { if(input)return summarize(input); const [mats,render,apps]=await Promise.all([safe(query,env,'SELECT state,hard_gates_pass,lease_expires_at,reused_from_job_id FROM material_versions ORDER BY id DESC LIMIT ?',[MAX_ROWS]),safe(query,env,'SELECT state,lease_expires_at FROM render_jobs ORDER BY id DESC LIMIT ?',[MAX_ROWS]),safe(query,env,'SELECT status AS state,updated_at FROM applications ORDER BY id DESC LIMIT ?',[MAX_ROWS])]); return summarize({material_versions:mats,render_jobs:render,generation:apps}); }
export function retentionGuard({versionedArtifactsLive=false,currentVersion,requestedVersions=[]}={}) { const current=String(currentVersion||''); const eligible=versionedArtifactsLive&&current&&requestedVersions.every(v=>String(v)!==current); return {allowed:Boolean(eligible),reason:eligible?'non_current_versions_only':'versioned_artifacts_live_and_non_current_required'}; }
function readInput(path){const value=JSON.parse(fs.readFileSync(path,'utf8'));return value&&typeof value==='object'?value:{};}
export function selfTest(){const r=summarize({now_ms:2000,generation:[{duration_ms:10,reused:true,jd_source:'ats'}],render_jobs:[{state:'pending'},{state:'claimed',lease_expires_at:'1970-01-01T00:00:01Z'}],material_versions:[{state:'claimed',hard_gates_pass:1,lease_expires_at:'1970-01-01T00:00:01Z'}]});if(r.generation.reuse!==1||r.stale_lease.render_jobs!==1||retentionGuard({versionedArtifactsLive:true,currentVersion:'a',requestedVersions:['a']}).allowed)throw new Error('health self-test failed');return r;}
if(import.meta.url==='file://'+process.argv[1]){try{const a=process.argv.slice(2);if(a.includes('--self-test'))console.log(JSON.stringify(selfTest(),null,2));else{const i=a.indexOf('--input');console.log(JSON.stringify(await loadReport({input:i>=0?readInput(a[i+1]):undefined}),null,2));}}catch{console.error('health report unavailable');process.exitCode=1;}}
