#!/usr/bin/env node
/** Bounded, deterministic, redacted operational report. */
import fs from 'node:fs'; import { tursoQuery } from './lib/turso.mjs';
export const MAX_ROWS=1000;
const rows=(x,name)=>{if(!Array.isArray(x)||x.length>MAX_ROWS)throw new Error('invalid '+name+' rows');if(x.some(r=>!r||typeof r!=='object'||Array.isArray(r)))throw new Error('invalid '+name+' row');return x;};
const durationRows=rs=>rs.map(x=>({...x,duration_ms:Number.isFinite(Date.parse(x.completed_at))&&Number.isFinite(Date.parse(x.created_at))?Date.parse(x.completed_at)-Date.parse(x.created_at):undefined}));
const bucket=(rs,k)=>Object.fromEntries(Object.entries(rs.reduce((a,r)=>{const v=String(r[k]??'unknown');const n=/^[A-Za-z0-9_.:-]{1,40}$/.test(v)?v:'unknown';a[n]=(a[n]||0)+1;return a;},{})).sort(([a],[b])=>a.localeCompare(b)));
const latency=rs=>{const v=rs.map(r=>Number(r.duration_ms)).filter(n=>Number.isFinite(n)&&n>=0&&n<=86400000).sort((a,b)=>a-b);return{count:v.length,min_ms:v[0]??0,max_ms:v.at(-1)??0,avg_ms:v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0};};
const required={material_versions:['state','hard_gates_pass','lease_expires_at','reused_from_job_id','attempt_count'],render_jobs:['state','lease_expires_at','created_at','completed_at','attempt_count'],applications:['status']};
const validate=(rs,name)=>{for(const r of rs)for(const k of required[name])if(!(k in r))throw new Error('invalid '+name+' schema');if(['material_versions','render_jobs'].includes(name))for(const r of rs){if(!['pending','claimed','succeeded','failed'].includes(r.state))throw new Error('invalid state');if(!Number.isInteger(r.attempt_count)||r.attempt_count<0)throw new Error('invalid attempt');for(const k of ['created_at','completed_at'])if(k in r&&r[k]!=null&&!Number.isFinite(Date.parse(r[k])))throw new Error('invalid date');}};
export function summarize(i={}){const m=durationRows(rows(i.material_versions||[],'material')),r=durationRows(rows(i.render_jobs||[],'render')),a=rows(i.applications||[],'application');validate(m,'material_versions');validate(r,'render_jobs');validate(a,'applications');const now=Number.isFinite(i.now_ms)?i.now_ms:Date.parse(i.as_of||''),stale=x=>x.state==='claimed'&&Number.isFinite(Date.parse(x.lease_expires_at))&&Date.parse(x.lease_expires_at)<now;return{generated_at:'deterministic',bounded:true,generation:{available:false,reason:'telemetry_unavailable',values:{}},material_lifecycle:{failed:m.filter(x=>x.state==='failed').length,claimed:m.filter(x=>x.state==='claimed').length,pending:m.filter(x=>x.state==='pending').length,attempts:m.reduce((n,x)=>n+(Number.isInteger(x.attempt_count)?x.attempt_count:0),0),reuse:m.filter(x=>x.reused_from_job_id!=null).length},render:{latency:latency(r),failures:r.filter(x=>x.state==='failed').length,claimed:r.filter(x=>x.state==='claimed').length,pending:r.filter(x=>x.state==='pending').length,attempts:r.reduce((n,x)=>n+(Number.isInteger(x.attempt_count)?x.attempt_count:0),0),queue_depth:r.filter(x=>['pending','claimed'].includes(x.state)).length,states:bucket(r,'state')},quality_gate:bucket(m,'hard_gates_pass'),jd_source:{available:false,reason:'telemetry_unavailable',values:{}},stale_lease:{materials:m.filter(stale).length,render_jobs:r.filter(stale).length},counts:{applications:a.length,materials:m.length,render:r.length},window:{timezone:'UTC',as_of_ms:Number.isFinite(now)?now:null}};}
export function retentionGuard(o={}){const ok=o.versionedArtifactsLive===true&&typeof o.currentPointer==='string'&&o.currentPointer.length>0&&typeof o.currentVersion==='string'&&o.currentVersion.length>0&&typeof o.currentHash==='string'&&o.currentHash.length>0&&o.manifestValid===true&&o.activeRenderJobs===0&&o.failedRenderJobs===0&&o.restoreProof===true&&Array.isArray(o.requestedVersions)&&o.requestedVersions.every(v=>String(v)!==o.currentVersion);return{allowed:ok,destructive:false,reason:ok?'guarded_non_current_only':'requires_live_pointer_version_hash_manifest_no_active_or_failed_render_restore_proof'};}
export function retentionPlan(o={}){const g=retentionGuard(o);return{...g,dry_run:true,delete_current:false,delete_legacy:false,targets:g.allowed?[...new Set((o.requestedVersions||[]).map(String))].filter(v=>v!==o.currentVersion).sort().slice(0,50):[]};}
export async function queryRows(query,env,sql,name){const result=await query(env,sql,[MAX_ROWS]);if(result&&result.ok===false)throw new Error('report query unavailable');const data=Array.isArray(result)?result:result?.rows;if(!Array.isArray(data))throw new Error('report query unavailable');return rows(data,name);}
export async function loadReport({env=process.env,query=tursoQuery,input}={}){if(input)return summarize(input);if(!env.TURSO_URL||!env.TURSO_TOKEN)throw new Error('report configuration unavailable');const qs=[['material_versions','SELECT state,hard_gates_pass,lease_expires_at,reused_from_job_id,attempt_count FROM material_versions ORDER BY id DESC LIMIT ?'],['render_jobs','SELECT state,lease_expires_at,created_at,completed_at,attempt_count FROM render_jobs ORDER BY id DESC LIMIT ?'],['applications','SELECT status FROM applications ORDER BY id DESC LIMIT ?']];const out=await Promise.all(qs.map(async([n,s])=>{try{return[n,await queryRows(query,env,s,n)];}catch{throw new Error('report query unavailable');}}));return summarize(Object.fromEntries(out));}
export function selfTest(){const x=summarize({now_ms:2000,material_versions:[{state:'failed',hard_gates_pass:0,lease_expires_at:null,reused_from_job_id:null,attempt_count:2,created_at:'2025-01-01T00:00:00Z',completed_at:'2025-01-01T00:00:01Z'}],render_jobs:[{state:'pending',lease_expires_at:null,created_at:'2025-01-01T00:00:00Z',completed_at:null,attempt_count:0},{state:'claimed',lease_expires_at:'1970-01-01T00:00:01Z',created_at:'1970-01-01T00:00:00Z',completed_at:null,attempt_count:1}]});if(x.render.queue_depth!==2||x.render.attempts!==1||x.stale_lease.render_jobs!==1||retentionGuard({versionedArtifactsLive:true,currentPointer:'p',currentVersion:'v',currentHash:'h',manifestValid:true,activeRenderJobs:0,failedRenderJobs:0,restoreProof:true,requestedVersions:['x']}).allowed!==true)throw new Error('health self-test failed');return x;}
if(import.meta.url==='file://'+process.argv[1]){try{const a=process.argv.slice(2),j=a.indexOf('--input');console.log(JSON.stringify(a.includes('--self-test')?selfTest():await loadReport({input:j>=0?JSON.parse(fs.readFileSync(a[j+1],'utf8')):undefined}),null,2));}catch{console.error('health report unavailable');process.exitCode=1;}}
