#!/usr/bin/env node
import { randomUUID } from 'node:crypto';
import { tursoQuery, tursoExecute } from './lib/turso.mjs';
import { acquireFetchLock } from './lib/lock.mjs';
import { validateManifestBytes } from '../functions/_lib/material-state.js';
export const MAX_ATTEMPTS=3, LEASE_SECONDS=600;
export function retryAfter(attempt,now=Date.now()){return now+Math.min(3600000,1000*2**Math.max(0,attempt-1));}
export function claimable(job,now=Date.now()){return job&&job.attempt_count<MAX_ATTEMPTS&&((job.state==='pending'&&(!job.retry_at||Date.parse(job.retry_at)<=now))||(job.state==='failed'&&job.retry_at&&Date.parse(job.retry_at)<=now)||(job.state==='claimed'&&Date.parse(job.lease_expires_at)<=now));}
export function claimSql(){return "UPDATE render_jobs SET state='claimed',lease_token=?,lease_expires_at=datetime('now','+' || ? || ' seconds'),attempt_count=attempt_count+1 WHERE id=? AND (state='pending' OR (state='failed' AND retry_at<=datetime('now')) OR (state='claimed' AND lease_expires_at<=datetime('now'))) AND attempt_count<?"}
export async function processRenderJob(row,{env,dryRun=false,execute=tursoExecute,query=tursoQuery,bucket,renderer}={}){if(dryRun)return{id:row.id,state:row.state,dryRun:true};const token=row.lease_token,expiry=row.lease_expires_at,attempt=Number(row.attempt_count),prefix=String(row.artifact_prefix||'');const live=async()=>{if(bucket?.checkLease)if(!(await bucket.checkLease(row)))throw Error('lease_stale');return true;const q=await query(env,"SELECT 1 FROM render_jobs WHERE id=? AND state='claimed' AND lease_token=? AND lease_expires_at=? AND attempt_count=?",[row.id,token,expiry,attempt]);if(!q?.length)throw Error('lease_stale')};const finish=async(ok,code='')=>{try{await live();const max=attempt>=MAX_ATTEMPTS;const sql=ok?"UPDATE render_jobs SET state='succeeded',completed_at=datetime('now'),error_code=NULL,retry_at=NULL,lease_token=NULL WHERE id=? AND state='claimed' AND lease_token=? AND lease_expires_at=? AND attempt_count=?":"UPDATE render_jobs SET state='failed',error_code=?,retry_at="+(max?'NULL':"datetime('now','+' || ? || ' seconds')")+",completed_at="+(max?"datetime('now')":"NULL")+",lease_token=NULL WHERE id=? AND state='claimed' AND lease_token=? AND lease_expires_at=? AND attempt_count=?";const args=ok?[row.id,token,expiry,attempt]:max?[String(code).slice(0,120),row.id,token,expiry,attempt]:[String(code).slice(0,120),Math.min(3600,2**Math.max(0,attempt-1)),row.id,token,expiry,attempt];const x=await execute(env,sql,args);return{id:row.id,state:Number(x?.affectedRowCount)===1?(ok?'succeeded':'failed'):'stale'}}catch{return{id:row.id,state:'stale'}}};const expected='materials/'+row.job_id+'/versions/'+String(row.version).toLowerCase()+'/'+prefix.split('/')[5];if(!/^materials\/\d+\/versions\/[a-f0-9]{64}\/[^/]+$/.test(prefix)||prefix!==expected)return finish(false,'source_prefix_invalid');try{const read=async n=>{await live();const x=await bucket.get(prefix+'/'+n);if(!x)throw Error('source_missing');return x.arrayBuffer?new Uint8Array(await x.arrayBuffer()):new TextEncoder().encode(await x.text())};const[m,r,c,d]=await Promise.all(['manifest.json','resume.md','cover_letter.md','job_details.json'].map(read));let manifest;try{manifest=JSON.parse(new TextDecoder().decode(m))}catch{throw Error('manifest_invalid')}if(!await validateManifestBytes(manifest,{resume:r,coverLetter:c,details:d},{jobId:row.job_id,version:row.version}))throw Error('source_tampered');const[a,b]=await Promise.all([renderer(new TextDecoder().decode(r),'resume'),renderer(new TextDecoder().decode(c),'cover_letter')]);if(!a?.ok||!b?.ok)throw Error('pdf_gates_failed');const staged=[[a,'resume.pdf'],[b,'cover_letter.pdf']];for(const[,n]of staged){await live();if(bucket.head&&await bucket.head(prefix+'/'+n))throw Error('pdf_exists')}for(const[x,n]of staged){await live();await bucket.put(prefix+'/'+n,x.body,{onlyIfNew:true})}return finish(true)}catch(e){return finish(false,e.message)}}
export async function pollRenderJobs({env,dryRun=false,limit=10,query=tursoQuery,execute=tursoExecute}={}){const rows=await query(env,"SELECT r.*,m.job_id,m.version,m.artifact_prefix FROM render_jobs r JOIN material_versions m ON m.id=r.material_version_id WHERE (r.state='pending' OR r.state='failed' OR (r.state='claimed' AND r.lease_expires_at<=datetime('now'))) AND r.attempt_count<? ORDER BY r.created_at LIMIT ?",[MAX_ATTEMPTS,Math.min(50,Math.max(1,limit))]);if(dryRun)return{dryRun:true,count:rows.length,rows:rows.map(r=>({id:r.id,state:r.state,attempt_count:r.attempt_count}))};const claimed=[];for(const row of rows){const token=randomUUID(),x=await execute(env,claimSql(),[token,LEASE_SECONDS,row.id,MAX_ATTEMPTS]);if(Number(x.affectedRowCount)===1)claimed.push({...row,lease_token:token})}return{dryRun:false,claimed}}
